// Query to check for successful logons from suspicious IPs
let TargetDevice = "windows-target-1";  // Replace with target VM
let SuspectIP = "89.116.158.44";  // Replace with suspect IP
DeviceLogonEvents
| where ActionType == "LogonSuccess"
| where DeviceName == TargetDevice and RemoteIP == SuspectIP
| order by TimeGenerated desc


DeviceLogonEvents
| where RemoteIP in ("218.92.0.187", "194.180.48.85", "196.251.84.225", "1.194.210.131", "185.7.214.81", "14.103.132.101")
| where ActionType != "LogonFailed"
